name: Deploy Colegio Frontend Amazon EKS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER }}
  IMAGE_TAG: ${{ github.sha }}-${{ github.run_attempt }}

jobs:
  deploy:
    name: Build, Push y Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag y push image frontend
        run: |
          docker build \
            --build-arg VITE_API_URL=/api \
            -t ${{ secrets.FRONTEND }}:${{ env.IMAGE_TAG }} \
            ./frontend-colegio-react

          docker push ${{ secrets.FRONTEND }}:${{ env.IMAGE_TAG }}

      - name: Update Kubeconfig EKS
        run: |
          aws eks update-kubeconfig \
            --name ${{ env.EKS_CLUSTER_NAME }} \
            --region ${{ env.AWS_REGION }}
      
      - name: Verificar nodos EKS
        run: |
          kubectl get nodes
          kubectl get nodes -o name | xargs -r -n1 kubectl wait --for=condition=Ready --timeout=300s
          kubectl get nodes -o custom-columns=NAME:.metadata.name,STATUS:.status.conditions[-1].type,TAINTS:.spec.taints

      - name: Deploy Frontend EKS
        env:
          FRONTEND: ${{ secrets.FRONTEND }}
        run: |
          cp k8s/front.yml k8s/front-rendered.yml

          sed -i "s|\${IMAGE_TAG}|$IMAGE_TAG|g" k8s/front-rendered.yml
          sed -i "s|\${FRONTEND}|$FRONTEND|g" k8s/front-rendered.yml

          kubectl apply -f k8s/front-rendered.yml

      - name: Verificar despliegue frontend
        run: |
          kubectl rollout status deployment/frontend-web --timeout=240s
          kubectl get pods
          kubectl get svc frontend-service
          kubectl get endpoints frontend-service
